theme: jekyll-theme-leap-day
theme: jekyll-theme-cayman
description: "Resources and representations for under-resourced languages and domains"
basepath: "resourceful-2023/"

navigation:
- text: Home
  url: /index.html
- text: Schedule
  url: /schedule.html
- text: Invited Speakers
  url: /invited_speakers.html
- text: Accepted Papers
  url: /papers.html
- text: Presentation Details
  url: /presentations.html

